### PR TITLE
Reindex rake task

### PR DESCRIPTION
**Pull request by ajays1991**
Hey, i implemented reindex support for chewy:index. 

Also i added repsec for actions for reindex method. Currently it has three cases.

1) should create a new index.
2) should copy the data from old_index to new_index without calling import or bothering primary database.
3) should copy data after updating the settings for the new index.

While for 3rd i was little stuck as i am looking a way/interface/method to change settings for a index on the fly so that i can validate the updated settings.

Maybe you can help.
Thanks

### CODE REVIEW

**Comment by ajays1991** [comment]
any thoughts?

**Comment by pyromaniac** [comment]
I like the idea, I'll merge this as soon as you will finish, such a task might be useful sometimes.

**Comment by ajays1991** [comment]
can you check last respec for action, to validate mapping changes. lmk

**Comment by pyromaniac** [comment]
I didn't quite get what am I supposed to do

**Comment by ajays1991** [comment]
ok

**Comment by ajays1991** [comment]
i will update PR and inform you later. Thanks

**Comment by furkanayhan** [comment]
any update on this?

**Comment by ajays1991** [comment]
@furkanayhan i have not resumed my work on this PR yet. I plan to resume this PR again as i have also found more usecases in terms of reindexing.

I am looking at the use case where i need to reindex the data with delta change, like adding the new field and building the source document for the delta changes.

Also i am looking at another usecase where i can specify additional settings for reindex including scripting, remote host.

This is getting interesting

**Comment by furkanayhan** [comment]
@ajays1991 looking forward to see it. thank you!

**Comment by mattzollinhofer** [comment]
@ajays1991: is this still something you’re working on?

**Pull request closed without merging**
