### PR TITLE
Rails 5 compatibility fixes

### PR DESCRIPTION
**Pull request by jesjos**
Fixes some deprecations introduced in Rails 5, up to beta 3.

- `Module#alias_method_chain`
- `ActiveRecord::QueryMethods#distinct`

### CODE REVIEW

**Comment by jesjos** [comment]
Some builds are failing, will fix this tomorrow (CET)

**Comment by pyromaniac** [comment]
Is it ready to be merged?

**Comment by jesjos** [comment]
@pyromaniac To my knowledge – yes.

**Comment by pyromaniac** [comment]
Perfect then, thanks!

**Pull request merged**
