### PR TITLE
Better initial strategies logging

### LINKED ISSUE #552: undefined method `debug`
With the latest version 0.10.0 I got a undefined method `debug` when booting my rails app.

The issue is introduced by this PR I believe: https://github.com/toptal/chewy/pull/543
I think we have a race condition here, since the `Chewy.logger` has been initialised yet because ActiveRecord isn't load. Because ActiveRecord `on_load` is used on [lib/chewy/railtie.rb#55](https://github.com/toptal/chewy/blob/master/lib/chewy/railtie.rb#L55), the time when the RequestStrategy is initialised, the Chewy.logger is still nil in my case.

Using Rails 5.1.3 on ruby 2.4.0

### PR DESCRIPTION
**Pull request by pyromaniac**
Fixes #552 
Instead of: #553

### CODE REVIEW

**Comment by arturtr** [comment]
@pyromaniac this logic requires initialize `Chewy.logger` in initializer

I solve this problem by this in initalizer
```ruby
Chewy.logger = Logger.new(nil)
```

**Comment by pyromaniac** [comment]
Is it with this PR included?

**Comment by arturtr** [comment]
Yes. This line 
https://github.com/toptal/chewy/blob/master/lib/chewy/railtie.rb#L53
broke rails to start 

because `Chewy.logger` is `nil` by default

**Comment by arturtr** [comment]
I catch this on run rails console

**Comment by pyromaniac** [comment]
Ah, console, got it, thanks. Will fix it

**Pull request merged**
