### PR TITLE
Fix ruby 2.7 warnings in rake tasks

### PR DESCRIPTION
**Pull request by aglushkov**

### CODE REVIEW

**Comment by rabotyaga** [comment]
Thank you very much @aglushkov !
Could you please add a changelog entry?

**Comment by aglushkov** [comment]
Changelog updated, was not sure such small PR should be mentioned in changelog )

**Comment by rabotyaga** [comment]
It's kinda user-visible, so why not.
Thanks again!

**Comment by dsantosmerino** [comment]
Hey @rabotyaga, we are trying to upgrade our app to use Ruby 3, but we saw that our Chewy-related tasks don't include this fix. We're using Chewy 5.2, and as far as I understood, it should include any non-specific Elastic version change, right?

**Comment by rabotyaga** [comment]
Hey @dsantosmerino 👋 !

Chewy 5.2 supports Elasticsearch 5.x (with a limited support for ES 1.x & 2.x).
Please refer to this table: https://github.com/toptal/chewy#elasticsearch-compatibility-matrix
If you're not limited in the selection of Elasticsearch versions, I'd recommend starting with Chewy 7.2.2 and latest 7.x ES.
Otherwise I'd recommend upgrading ES and Chewy versions gradually as per https://github.com/toptal/chewy/blob/master/migration_guide.md.

**Comment by dsantosmerino** [comment]
We use 6.4 ES, I'll try upgrading to Chewy 6.x then. Thanks, @rabotyaga for your quick response!

**Comment by olancheg** [comment]
hi! could you back port this fix to 7.0.X branch please?

```
$ rake chewy:upgrade
rake aborted!
ArgumentError: wrong number of arguments (given 1, expected 0)
/Users/olancheg/.rvm/gems/ruby-3.0.3/gems/chewy-7.0.1/lib/chewy/rake_helper.rb:62:in `upgrade'
/Users/olancheg/.rvm/gems/ruby-3.0.3/gems/chewy-7.0.1/lib/tasks/chewy.rake:31:in `block (2 levels) in <top (required)>'
/Users/olancheg/.rvm/gems/ruby-3.0.3/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/Users/olancheg/.rvm/gems/ruby-3.0.3/bin/ruby_executable_hooks:22:in `eval'
/Users/olancheg/.rvm/gems/ruby-3.0.3/bin/ruby_executable_hooks:22:in `<main>'
Tasks: TOP => chewy:upgrade
(See full trace by running task with --trace)
```

**Comment by rabotyaga** [comment]
Hey @olancheg 👋 !
I'd rather encourage you to ugrade to _at least_ 7.1.0. Or even 7.2.3. Is there anything that blocks you from this?

**Comment by olancheg** [comment]
hey @rabotyaga ,
thanks for getting back to me!
since I'm still on 6.8 ES, and chewy 7.0.X branch being the last to support ES 6 versions.
definitely going to upgrade to ES 7 in due course, though I don't think I'm the only one with this issue :)

**Comment by rabotyaga** [comment]
@olancheg It seems 6.8 is reaching EOL in less than 1 month: https://www.elastic.co/support/eol
We will not backport fixes to 7.0 branch. Sorry.

**Pull request merged**
