### PR TITLE
Encapsulate rake helper methods

### PR DESCRIPTION
**Pull request by caldwecr**
This PR moves existing rake helper method logic into an isolated module / file.

### CODE REVIEW

**Comment by caldwecr** [comment]
Please don't merge this yet. I believe these methods may not be covered by specs. I'd like to see that resolved before the merge as there's no suitable way to test without it.

**Comment by pyromaniac** [comment]
Ok, how about extend self and use method directly in rake without inclusion?

**Comment by caldwecr** [comment]
@pyromaniac - sure; just to be clear you want me to turn RakeHelper into a singleton and expose the methods on the module directly, right? And then invoke them in the rake task as RakeHelper.method_name

**Comment by pyromaniac** [comment]
A kind of, but I'm just offering since I've got no opinion on this, so don't hesitate to choose the best approach and implement it :)

**Comment by caldwecr** [comment]
Ok @pyromaniac I think this should be good.

**Comment by pyromaniac** [comment]
Thanks!

**Pull request merged**
