### PR TITLE
Add KNN

### PR DESCRIPTION
**Pull request by jkostolansky**
Add the [KNN](https://www.elastic.co/guide/en/elasticsearch/reference/current/knn-search.html) option to the request.

```ruby
PlacesIndex.knn(field: :vector, query_vector: [4, 2], k: 5, num_candidates: 50)
# => <PlacesIndex::Query {..., :body=>{:knn=>{"field"=>:vector, "query_vector"=>[4, 2], "k"=>5, "num_candidates"=>50}}}>
```

### CODE REVIEW

**Comment by tomdev** [comment]
This sounds like a great feature addition! Is there anything we need to do before this PR can get reviewed?

**Comment by konalegi** [comment]
Folks, sorry for the long absence, is this feature still legit?

**Comment by konalegi** [comment]
@jkostolansky could you please rebase with master and update your branch? (ofc as long as you need this PR)

**Comment by jkostolansky** [comment]
@konalegi Sure, it's rebased. Thanks!

**Review by konalegi — APPROVED** [review]

**Comment by konalegi** [comment]
hey @jkostolansky your changes has been release https://rubygems.org/gems/chewy/versions/7.3.6

**Comment by jkostolansky** [comment]
Thank you, @konalegi 🙌

**Pull request merged**
