### PR TITLE
Bump version to 7.6.0

### PR DESCRIPTION
**Pull request by konalegi**
Bump Version to 7.6.0

### CODE REVIEW

**Comment by mjankowski** [comment]
It seems like these rake_helper intermittent errors are timeout-related ... I wasn't able to replicate locally. Presumably the connection between the suite running on CI and the ES server in the CI env is slower or less reliable than when they are running right next to each other on localhost...

Is there a straightforward way (for test env only?) to make the timeout value higher?

**Comment by konalegi** [comment]
@mjankowski  Sorry, I probably missing what we are talking about. Are talking about flaky CI?

**Comment by mjankowski** [comment]
Yes, sorry -- my comment had nothing to do with the 7.6.0 release in this PR ... just noticed the failing specs and saw they were the same flaky issue from the other PRs.

**Comment by konalegi** [comment]
> Yes, sorry -- my comment had nothing to do with the 7.6.0 release in this PR ... just noticed the failing specs and saw they were the same flaky issue from the other PRs.

I'll Look at this later, but if you want to find an issue, feel free to ping me, I'm ready to assist you about it.

**Comment by konalegi** [comment]
@toptal-anvil ping reviewers

**Comment by konalegi** [comment]
@toptal-anvil ping reviewers

**Review by skcc321 — APPROVED** [review]

**Review by AlexVPopov — APPROVED** [review]

**Review by barthez — APPROVED** [review]

**Comment by konalegi** [comment]
Chewy released https://rubygems.org/gems/chewy

**Comment by mjankowski** [comment]
Thanks!

**Pull request merged**
