### PR TITLE
Reset import opts

### PR DESCRIPTION
**Pull request by cokuyan**
Allows the `#reset!` method to accept an options hash, specifically to allow the `#import` method to implement those options. This fork was originally created to allow passing in the `batch_size` option to the inner `#import` method.

### CODE REVIEW

**Comment by pyromaniac** [comment]
Well, right now you are able to specify import options per type, don't see why would you need different options for usual importing and reset

**Comment by cokuyan** [comment]
What do you mean?
We needed to find a way to use the `reset!` method since it allows for creating an alias while the indexing occurs, whereas just doing a normal `import` would not create an alias during indexing.

**Comment by pyromaniac** [comment]
Reset uses #import, #import uses https://github.com/toptal/chewy#type-default-import-options

**Comment by cokuyan** [comment]
O, I didn't see that before. That definitely should solve the issue we had. Thanks!

**Comment by pyromaniac** [comment]
So, did it help, can we close this PR?

**Comment by cokuyan** [comment]
yea, go ahead

**Pull request closed without merging**
