### PR TITLE
Drop support for Ruby 2.6

### PR DESCRIPTION
**Pull request by alejandroperea**
Ruby 2.6 reached its EOL almost 2 years ago.

-----------------

Before submitting the PR make sure the following are checked:

* [ ] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [ ] Wrote [good commit messages][1].
* [ ] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [ ] Feature branch is up-to-date with `master` (if not - rebase it).
* [ ] Squashed related commits together.
* [ ] Added tests.
* [ ] Added an entry to the changelog if the new code introduces user-observable changes. See [changelog entry format](https://github.com/toptal/chewy/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by konalegi** [comment]
Thank you for your PR, I'll need to think about dropping support for whole ruby 2.x, since both 2.7 and 2.6 are already reached end of life.
So I'll probably close it and provide my own PR with ruby 2.x clean-up.

**Comment by konalegi** [comment]
Ok, I'm going to clean-up from all ruby 2.x this week, so closing this PR. Thanks for bringing that topic.

**Comment by alejandroperea** [comment]
Thanks @konalegi !

**Comment by konalegi** [comment]
FYI https://github.com/toptal/chewy/pull/911

**Pull request closed without merging**
