### PR TITLE
ActiveJob strategy

### PR DESCRIPTION
**Pull request by mkcode**
I recently upgraded my Rails app to use ActiveJob and thought chewy could use it too. 

This works for me in my application. Tests pass for me as well. Was not sure about how or if this needs any additional Appraisal setup.

Cheers!

### CODE REVIEW

**Comment by pyromaniac** [comment]
Such an awesome contribution! Thanks!

**Comment by mkcode** [comment]
@pyromaniac - thanks! It doesn't look like Travis is running the tests for this, we may need to add ActiveJob to the appraisals.  It looks like ActiveJob does only work with Rails 4.2

**Comment by pyromaniac** [comment]
Yep, it seems like it makes sense since it doesn't looks like ActiveJob specs were run fro 4.2 (comparing https://travis-ci.org/toptal/chewy/jobs/84459146 and https://travis-ci.org/toptal/chewy/jobs/84459149)

**Comment by mkcode** [comment]
Not sure what is happening with the appraisals. https://github.com/mkcode/chewy/commit/da1108ac43b6baeaf9b0cd17bf1ce15d5c7aa2f1 did not it.

**Comment by pyromaniac** [comment]
Hm, you probably have to regenerate gemfiles :)

**Comment by mkcode** [comment]
Alright! That did it!

**Comment by pyromaniac** [comment]
It seems like you forgot to comment back everything you've uncommented in the main Gemfile :(

**Comment by mkcode** [comment]
I had only changed the one line I added: https://github.com/mkcode/chewy/commit/2a890ae6666fe8c7a2f717c94429ffd76fa73639. I'll get rid of those others too though.

**Comment by mkcode** [comment]
Ok! That should do it - in a few hours when it's done building. :-)

**Comment by pyromaniac** [comment]
Thanks!

**Comment by mkcode** [comment]
Thanks for the merge! 

I would appreciate a new gem release if its easy. :smile: :gem:

**Pull request merged**
