### PR TITLE
add able to use Proc for settings

### PR DESCRIPTION
**Pull request by parallel588**

### CODE REVIEW

**Comment by pyromaniac** [comment]
Hey, can you provide a reasoning as well as a couple of specs here please?

**Comment by parallel588** [comment]
Hi Arkadiy (@pyromaniac), I added test.
about case where it may be use:
if we keep  a synonyms/stopwords in db then in the settings we can use synonyms from db
for instance:
```
 class ProductsIndex < Chewy::Index
  settings proc {
    {
      analysis: {
        filter: {
          synonym: {
            type: 'synonym',
            ignore_case: true,
            synonyms: SearchSynonym.synonyms
          },
          
          custom_stop: {
            type: 'stop',
            stopwords: SearchStopWord.terms
          },
.....
```

and we can update settings after changes SearchSynonym.synonyms

```
   Chewy.client.indices.put_settings(
        index: productsIndex.index_name,
        body: {
          index: {
            analysis: {
              filter: {
                synonym: {
                  synonyms: SearchSynonym.synonyms
                }
              } } } }
      )

```

**Comment by pyromaniac** [comment]
Interesting, I would like to merge this, but can you fix a DSL here please? I would prefer

```
settings do

end
```

And rebase. And I'll merge it right away, thanks for the great idea.

**Comment by pyromaniac** [comment]
Never mind, I'll do it by myself later, thanks for the great idea!

**Pull request closed without merging**
