### PR TITLE
Fixed all deprecation warnings in Ruby 2.7

### PR DESCRIPTION
**Pull request by gseddon**
Addresses https://github.com/toptal/chewy/issues/700
All tests are passing

### CODE REVIEW

**Comment by mrzasa** [comment]
@gseddon first of all - thank for for the fix!
Could you, please, rebase on the newest master, so that we can run tests on CI before merging it? Ruby 2.7 has been just added to the test matrix.

**Comment by mrzasa** [comment]
Pls, one more push and this time it'll surely work ;-) (just got forks build enabled)

**Comment by gseddon** [comment]
Let's see how this goes!

**Comment by mrzasa** [comment]
Great it worked! Merging.

**Comment by schinery** [comment]
@mrzasa do you know when we might see a new Chewy release with this PR in?

**Comment by andyatkinson** [comment]
Looking forward to a new Chewy release to address 2.7 deprecation warnings!

**Comment by Bodacious** [comment]
Any update on this issue please?

**Comment by AlfonsoUceda** [comment]
Hi folks, we are going to release a new version where these deprecations warnings in Ruby 2.7 has been fixed.

**Pull request merged**
